openapi: 3.0.1
info:
  title: Praise & Regret Logger
  description: A simple rest api to log praise and regret into a database
  version: 1.0.0

tags:
  - name: Logger
    description: API to log praise and regret

paths:
  /api/log:
    post:
      tags:
        - Logger
      summary: Create a new log
      operationId: log
      security:
        - bearer: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LogRequest"
      responses:
        201:
          description: The log was created successfully
        403:
          description: Not authorized to create a log
        500:
          description: Things went wrong

components:
  schemas:
    LogRequest:
      type: object
      description: Request to create a new log
      required:
        - type
      properties:
        type:
          $ref: "#/components/schemas/LogType"
          example: PRAISE


    LogType:
      type: string
      nullable: false
      description: The type of log
      enum:
        - PRAISE
        - REGRET

  securitySchemes:
    bearer:
      type: http
      description: API token
      scheme: bearer
